### ISSUE TITLE
ifstat path

### ISSUE THREAD

**Issue by volcacius** [deep500/deep500#1]
Hi,

ifstat path is assumed to be /usr/sbin/ifstat, which is not necessarily always the case. A better option would be to use _shutil.which()_ to determine the path ([link](https://docs.python.org/3/library/shutil.html?highlight=.which#shutil.which) to docs), which is part of Python 3.3+. 

Alessandro

**Comment by tbennun** [comment]
Hi,

That's a great idea! Could you issue a pull request please?

**Comment by tbennun** [comment]
Fixed in d79692b76d34282b1d8115dfc5311b9a0bc720ad.
